#! /usr/bin/env bash

function convertToScript {
  while IFS='' read -r p; do

    hidden=$(echo $p | sed -n 's/^$#/$/p')

    if [ -n "$hidden" ] ; then
      p=$hidden
    else
      safe=$(echo "$p" | sed "s/'/'\\\\''/g; s/^/'/; s/$/'/") # replace ' with '\'', wrap in single quotes
      # echo "DEBUG    p=$p"
      # echo "DEBUG safe=$safe"
      echo "echo $safe"
    fi

    command=$(echo $p | sed -n 's/^$ //p')

    if [ -n "$command" ] ; then
      echo "$command"
    fi
  done
}

convertToScript | bash 2>&1
